code/src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $places = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $beginDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    /**
     * @var Collection<int, Intern>
     */
    #[ORM\ManyToMany(targetEntity: Intern::class, mappedBy: 'sessions')]
    private Collection $interns;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(name: "trainer_id", referencedColumnName: "id", onDelete: "SET NULL")]
    private ?Trainer $trainer = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(name: "training_id", referencedColumnName: "id", onDelete: "SET NULL")]
    private ?Training $training = null;

    /**
     * @var Collection<int, Program>
     */
    #[ORM\OneToMany(targetEntity: Program::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $programs;

    public function __construct()
    {
        $this->interns = new ArrayCollection();
        $this->programs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): static
    {
        $this->places = $places;

        return $this;
    }

    public function getBeginDate(): ?\DateTimeInterface
    {
        return $this->beginDate;
    }

    public function setBeginDate(\DateTimeInterface $beginDate): static
    {
        $this->beginDate = $beginDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    /**
     * @return Collection<int, Intern>
     */
    public function getInterns(): Collection
    {
        return $this->interns;
    }

    public function addIntern(Intern $intern): static
    {
        if (!$this->interns->contains($intern)) {
            $this->interns->add($intern);
            $intern->addSession($this);
        }

        return $this;
    }

    public function removeIntern(Intern $intern): static
    {
        if ($this->interns->removeElement($intern)) {
            $intern->removeSession($this);
        }

        return $this;
    }

    public function getTrainer(): ?Trainer
    {
        return $this->trainer;
    }

    public function setTrainer(?Trainer $trainer): static
    {
        $this->trainer = $trainer;

        return $this;
    }

    public function getTraining(): ?Training
    {
        return $this->training;
    }

    public function setTraining(?Training $training): static
    {
        $this->training = $training;

        return $this;
    }

    /**
     * @return Collection<int, Program>
     */
    public function getPrograms(): Collection
    {
        return $this->programs;
    }

    public function addProgram(Program $program): static
    {
        if (!$this->programs->contains($program)) {
            $this->programs->add($program);
            $program->setSession($this);
        }

        return $this;
    }

    public function removeProgram(Program $program): static
    {
        if ($this->programs->removeElement($program)) {
            // set the owning side to null (unless already changed)
            if ($program->getSession() === $this) {
                $program->setSession(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?array
    {

        $currentDate = new \DateTime();
        $sessionStatus = [
            'label' => 'Finished',
            'class' => 'danger'
        ];

        if ($this->getBeginDate() <= $currentDate && $this->getEndDate() >= $currentDate) {
            $sessionStatus = [
                'label' => 'In Progress',
                'class' => 'active'
            ];
        } else if ($this->getBeginDate() > $currentDate) {
            $sessionStatus = [
                'label' => 'Planned',
                'class' => 'neutral'
            ];
        }

        return $sessionStatus;
    }

    public function getTotalDays(){
        
        $total = array_reduce($this->programs->toArray(), function($total, $program){
            return $total + $program->getTotalDays();
        } , 0);

        return $total;
    }
}

code/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Training;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class HomeController extends AbstractController{
    #[Route('/', name: 'home_index')]
    public function index(EntityManagerInterface $entityManager): Response
    {

        $sessionsData = $entityManager->getRepository(Session::class)->getGlobalInfos();
        $trainingsData = $entityManager->getRepository(Training::class)->getLastTrainings();
        return $this->render('home/index.html.twig', [
            'sessionsData' => $sessionsData,
            'trainingsData' => $trainingsData
        ]);
    }
}

code/templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
    <link rel="stylesheet" href={{asset('css/home.css')}}>
{% endblock %}


{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <script src="{{asset('js/home.js')}}" defer></script>
{% endblock %}

{% block title %} Home {% endblock %}
{% block pageTitle %} Manage your Formation Center {% endblock %}
{% block pageDesc %} Take a look at the overall informations {% endblock %}

{% block body %}
    <div class="home">
        <section class="info-cards">
            <div class="card trainings">
                <i class="fa-solid fa-ellipsis-vertical card-menu"></i>
                <div class="trainings-container">
                    <section class="splide" aria-label="Splide Basic HTML Example">
                        <div class="splide__track">
                            <ul class="splide__list">
                            {% for training in trainingsData %}
                                <li class="splide__slide">
                                    <p class="trainer-tag">
                                        <i class="fa-solid fa-user-tie"></i>
                                        <span>{{training.trainerCount ?? 0}} trainers</span>
                                    </p>
                                    <div class="slide-container">
                                        <h5>{{training.name}}</h5>
                                        <div class="stats">
                                            <div class="item">
                                                <span>{{training.sessionCount ?? 0}}</span>
                                                <span>Sessions</span>
                                            </div>
                                            <div class="item">
                                                <span>{{training.moduleCount ?? 0}}</span>
                                                <span>Modules</span>
                                            </div>
                                            <div class="item">
                                                <span>{{training.internCount ?? 0}}</span>
                                                <span>Interns</span>
                                            </div>
                                            <div class="item">
                                                <span>{{training.totalDays ?? 0}}</span>
                                                <span>Days</span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                            </ul>
                        </div>
                    </section>
                </div>
                <a href={{path("training_index")}}>See all trainings</a>
            </div>
            <div class="card sessions">
                <header>
                    <h3>Sessions</h3>
                    <i class="fa-solid fa-ellipsis-vertical"></i>
                </header>
                <div class="sessions-container">
                    <div class="session-row general">
                        <div class="session-created">
                            <span>{{sessionsData.totalSessions}}</span>
                            <p>Sessions created</p>
                        </div>
                        <div class="last-session">
                            <span>{{sessionsData.lastCreatedSession}}</span>
                            <p>Last Sessions created</p>
                        </div>
                    </div>
                    <div class="session-row bonus">
                        <div class="card">
                            <i class="fa-solid fa-dolly"></i>
                            <div class="stats">
                                <span>{{sessionsData.upcomingSessionsCount}}</span>
                                <p>upcoming</p>
                            </div>
                        </div>
                        <div class="card">
                            <i class="fa-solid fa-truck-fast"></i>
                            <div class="stats">
                                <span>{{sessionsData.onGoingSessionsCount}}</span>
                                <p>ongoing</p>
                            </div>
                        </div>
                        <div class="card">
                            <i class="fa-solid fa-circle-check"></i>
                            <div class="stats">
                                <span>{{sessionsData.finishedSessionsCount}}</span>
                                <p>finished</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card quick-actions">
                <header>
                    <h3>Quick actions</h3>
                    <i class="fa-solid fa-ellipsis-vertical"></i>
                </header>
                <div class="actions-container">
                    <div class="action-section">
                        <p>Users</p>
                        <div class="actions">
                            <a href={{path("intern_add")}}>
                                <i class="fa-solid fa-user-plus"></i>
                                <span>Add an intern</span>
                            </a>
                            <a href={{path("trainer_add")}}>
                                <i class="fa-solid fa-user-plus"></i>
                                <span>Add an trainer</span>
                            </a>
                        </div>
                    </div>
                    <div class="action-section">
                        <p>Sessions & more</p>
                        <div class="actions">
                            <a href={{path("session_add")}}>
                                <i class="fa-solid fa-plus"></i>
                                <span>Create a session</span>
                            </a>
                            <a href={{path("training_add")}}>
                                <i class="fa-solid fa-plus"></i>
                                <span>Create a training</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="sub-section">
            <h3>Logs</h3>
            <div class="logs-feed">
                <ul class="log-list">
                    <li class="log-item">
                        <span class="log-time">10/04/25 10:07</span>
                        <span class="separator">-</span>
                        <span class="log-user">Louis Hayotte</span>
                        <span class="separator">:</span>
                        <span class="log-message">Created a new training called "Menuisier"</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">10/03/25 13:45</span>
                        <span class="separator">-</span>
                        <span class="log-user">Stephane Smail</span>
                        <span class="separator">:</span>
                        <span class="log-message">Added a new Intern : Gérard chambouin</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">10/03/25 13:43</span>
                        <span class="separator">-</span>
                        <span class="log-user">Stephane Smail</span>
                        <span class="separator">:</span>
                        <span class="log-message">Deleted an Intern : Marine fugui</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">10/03/25 13:43</span>
                        <span class="separator">-</span>
                        <span class="log-user">Stephane Smail</span>
                        <span class="separator">:</span>
                        <span class="log-message">Added a new Intern : Marine fugui</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">10/01/25 23:40</span>
                        <span class="separator">-</span>
                        <span class="log-user">Mickael Murmann</span>
                        <span class="separator">:</span>
                        <span class="log-message">Created a new session called "Formation SQL & requêtes avancées."</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">10/01/25 23:32</span>
                        <span class="separator">-</span>
                        <span class="log-user">Mickael Murmann</span>
                        <span class="separator">:</span>
                        <span class="log-message">Created a new session called "RGPD et politique de confidentialité"</span>
                    </li>
                    <li class="log-item">
                        <span class="log-time">22/12/24 23:40</span>
                        <span class="separator">-</span>
                        <span class="log-user">Louis Hayotte</span>
                        <span class="separator">:</span>
                        <span class="log-message">Created a new trainer called "Mickael Murmann"</span>
                    </li>
                </ul>
            </div>
        </section>
    </div>

{% endblock %}